plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.107'
}

version = mod_version
group = mod_group_id

base { archivesName = mod_id }

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version
    runs {
        client { client() }
        server { server() }
    }
    mods {
        "${mod_id}" { sourceSet(sourceSets.main) }
    }
}

repositories {
    mavenCentral()
    maven { url = 'https://maven.createmod.net' }
}

dependencies {
    compileOnly("com.simibubi.create:create-1.21.1:6.0.10-280:slim") { transitive = false }
}

processResources {
    var props = [mod_id: mod_id, mod_version: mod_version]
    inputs.properties props
    filesMatching('META-INF/neoforge.mods.toml') { expand props }
}
