modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "SatLink"
description = '''
Satellite dish, ground station, solar panels and energy storage.
Create optional (goggles show panel/storage energy).
'''

[[dependencies.satlink]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.satlink]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.satlink]]
modId = "create"
type = "optional"
versionRange = "[6.0.0,)"
ordering = "AFTER"
side = "BOTH"
